# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -o ./out/foxyfy ./cmd/foxyfy
  run:
    cmds:
      - go run ./cmd/foxyfy/main.go
  test:
    cmds:
      - go test ./...